### ISSUE TITLE
Android SDK Offline Testing

### ISSUE THREAD

**Issue by midhunQburst** [braintree/braintree_android#11]
Is there any similar methods for offline testing in Android like the one in iOS (BTClient+Offline.h) ?.

**Comment by lkorth** [comment]
Closing this old issue. If anyone else has feedback, please feel free to comment.

**Comment by janumanuhu** [comment]
I would like to integrate Braintree SDK into my Android app. But the way to display Drop-In UI is different as per my requirement. Currently as per Demo shows code, once we click on Drop-In button it will open new Activity of Braintree. But as per my requirement I want to display Drop-In UI in my application page only and then after once I clicked on my BUY button braintree payment should perform and return me Nonce value so that I can send that to server. One more point is, how can I test my integration is working or not? Is there any dummy testing Braintree provided? Thank You in advance.

**Comment by lkorth** [comment]
@janumanuhu this issue is not related to Drop-in.
