### ISSUE TITLE
Hungarian language support

### ISSUE THREAD

**Issue by balazsgerlei** [braintree/braintree_android#111]
Hi!
We are planning to use the Braintree SDK in an app with Hungarian language support and we wondered if it is possible to add Hungarian language to the UI of the Braintree SDK as well. We are willing to translate it ourselves via Pull request, I just wanted to ask it first.

Thank you in advance!

**Comment by lkorth** [comment]
Just to make sure it's clear, translations are only required if you're using Drop-in, if you are not, there are no user facing strings in the SDK.

I will pass this request along to our product development team that handles translations. Unfortunately we typically do not accept translations via pull request because in the future when strings change we need to support and maintain them with our translation team.

**Comment by balazsgerlei** [comment]
Yeah, I know that it is only required for the Drop-in UI, that's what I would like in Hungarian. Ok, thank you for forwarding the request, I hope the translation will be made. If we could help in any other way (maybe just sending the translation of current strings), let me know! Thank you!

By the way, I submitted a similar issue for the iOS version of the SDK, could you pass that on to the team who handles translations? Thank you!
https://github.com/braintree/braintree_ios/issues/252
