### ISSUE TITLE
Incorrect Android Pay onCancel callback behaviour

### ISSUE THREAD

**Issue by RadoslawHardyl** [braintree/braintree_android#145]
Hey guys,

We're using latest SDK ver 2.5.1, and we find strange BraintreeFragment behaviour connected with Android Pay(integration with AndroidPayActivity).
Basically if you start Android Pay flow twice, and in second try you will just close Android Pay Activity(e.g. back button),
instead of "onCancel" callback, you will get success callback with nonce generated in first try.

steps to reproduce:
1. start Android Pay Activity `AndroidPay.requestAndroidPay(fragment,...);`
2. select AP card and confirm
3. receive Android Pay nonce
4. start Android Pay Activity
5. tap back button(close Android Pay Activity)

AC:
onCancel callback is launched

Actual Results:
onPaymentMethodNonceCreated is launched with AP nonce from point 3.

Best
Radek

**Comment by sdcoffey** [comment]
Hey @RadoslawHardyl 

Thanks for submitting this bug report. It's been a week since you've submitted this issue, so I wanted to follow up and see if you were still running into it. I was not able to reproduce in our demo app using the version you provided. If this is still happening for you, let me know and we can debug from there.

**Comment by sdcoffey** [comment]
Hey @RadoslawHardyl,

I'm going to close this issue due to inactivity. Feel free to open a new issue if you're still experiencing this behavior.
