### ISSUE TITLE
libpng warning when compiling with gradle

### ISSUE THREAD

**Issue by designatednerd** [braintree/braintree_android#16]
Every time I build using Gradle on Android Studio, I get warnings of this type for pretty much every drawable resource in your library: 

```
[path to project]/com.braintreepayments.api/braintree/1.2.7/res/drawable-mdpi-v4/bt_loading.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
```

Is there some kind of setting I should be looking at to ignore this on my end? Or is this something you guys can fix on your end?

**Comment by lkorth** [comment]
@designatednerd did this answer your issue?

**Comment by designatednerd** [comment]
@lkorth Yes, but I'd recommend leaving this open until the noise goes away so that anyone else encountering this issue is able to see what the problem is.

**Comment by imminent** [comment]
https://groups.google.com/forum/#!msg/adt-dev/rjTQ_STR3OE/-UcNQRISTKsJ has a solution for this. Just need to clean up the metadata on the PNGs.

**Comment by lkorth** [comment]
Stripped assets coming soon to a release near you!

**Comment by imminent** [comment]
Thanks!

**Comment by designatednerd** [comment]
:+1:

**Comment by lkorth** [comment]
Just to note, there will still be some warnings generated because of the [card form](https://github.com/braintree/braintree_android/blob/master/Drop-In/build.gradle#L23). I have made the [commit to strip the metadata](https://github.com/braintree/android-card-form/commit/f8d6bf494bc642a8d2639e178816a1ab8eee7273) in the card form, however it won't take effect until the next version of the card form is released and Drop-in is update.
