### ISSUE TITLE
Multiple listeners

### ISSUE THREAD

**Issue by mlykotom** [braintree/braintree_android#160]
### General information

* SDK/Library version: 2.5.4
* Environment: both
* Android Version and Device: Oneplus 3T - Android 7.1.1 (but doesn't matter)

### Issue description
I have one activity with 2 fragments (list, detail) and initialise BraintreeFragment in both fragments (because PayPal is handled in list and credit card in detail).

The problem is method `addListener()` which actually doesn't add listener, but **set it** instead.

I "add" listeners (error, nonceCreated) after called `BraintreeFragment.newInstance()` and remove in `onDestroyView()`. 
What actually happens when going from "list" fragment to "detail" fragment:

0)`onViewCreated` (list fragment) -> sets listener 
1)`onViewCreated` (detail fragment)  -> overrides listener from previous fragment
2)`onDestroyView` (list fragment) -> removes listener from the next fragment 

I suggest, that `addListener` and `removeListener` methods should use some collection to store the listeners in order this doesn't happen.

The same would happen if someone used tablet layout with master,detail screen and would want to have listeners in both fragments.

**Comment by lkorth** [comment]
`addListener` is probably the wrong name for this method, you're right that it only [allows a single listener of each type to be set](https://github.com/braintree/braintree_android/blob/b02a879994f2442d60187fead64239df3366ea92/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L350).

Only a single listener of each type is allowed primarily because callbacks can happen outside of some parts of the `Activity` lifecycle when no listeners are present. `BraintreeFragment` [queues these callbacks](https://github.com/braintree/braintree_android/blob/b02a879994f2442d60187fead64239df3366ea92/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L604) if no listener is present and sends them the next time a given listener is set.

To make this work for your use case, you'll probably need to register your `Activity` as all of the listeners you need and then propagate those callbacks to the correct `Fragment` when you receive them.

**Comment by sdcoffey** [comment]
Hey @mlykotom,

Just wanted to see if @lkorth's suggestion was working for you. Let us know if you're still experiencing issues.

**Comment by sdcoffey** [comment]
Whoops, didn't mean to close this, sorry!

**Comment by mlykotom** [comment]
I did my own workaround, which removes listener before showing the next screen.

I think it would be possible to use some collection of the listeners which would prevent this problems.

"Naive" solution - having list for every listener. 
More robust - just one collection for all listeners.

**Comment by sdcoffey** [comment]
@mlykotom,

I think you're right that a better solution than the one we have is to modify the behavior to match the semantics here. Unfortunately, doing this now would be a behavioral change and could have unintended consequences for other merchants depending on the current behavior. We'll keep this in mind as we develop our roadmap and let you know if we expect this behavior to change in a future version.
