### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by ramanclabs** [braintree/braintree_android#17]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/paypal/android/sdk/payments/PayPalService;
![screen shot 2015-01-23 at 11 18 16 am](https://cloud.githubusercontent.com/assets/1811924/5870349/980e4c6a-a2f1-11e4-8482-8a49947b1f15.png)

I am Using Eclipse and braintree-api-1.2.7-full.jar

**Comment by lkorth** [comment]
If you inspect the jar, the class is there. Do you have a way to reproduce this or any other information? Are you using ProGuard?

**Comment by ramanclabs** [comment]
I am not using ProGuard. And when I inspect the jar, the class is there. It is present at compile time. 
I have Defined the PayPalService and other Paypal classes in the Manifest as well.

*After getting clientToken from server I am calling:
braintree.startPayWithPayPal(EvidenceStorage.this, PAYPAL_REQUEST_CODE);
after this point the app crashes.

**Comment by lkorth** [comment]
It appears that this is an [open issue in the PayPal SDK](https://github.com/paypal/PayPal-Android-SDK/issues/90) and still being investigated. It seems to be limited to just Eclipse and Ant. We recommend developers use [Android Studio](http://developer.android.com/sdk/index.html) going forward since it is the officially supported and recommended IDE for Android development.

**Comment by ramanclabs** [comment]
Is there some way to make it work with eclipse itself?

**Comment by lkorth** [comment]
It is unclear why it happens using Ant and Eclipse, so there is not a known way to make it work. There is a new version of the SDK due out shortly this also includes a new version of the PayPal SDK, so it is possible that it will improve or fix your issue.

**Comment by ramanclabs** [comment]
Hi, I managed to run my eclipse braintree code. But the problem is I am only getting paypal Login screen directly and not the option to choose from paypal or credit card.

**Comment by lkorth** [comment]
Correct, `braintree.startPayWithPayPal(activity, PAYPAL_REQUEST_CODE)` will start the PayPal flow. In order to handle credit cards you must build your own form and use `Braintree#tokenize`. You can find more information about accepting credit cards on Android in our [docs](https://developers.braintreepayments.com/android+ruby/sdk/client/credit-cards).

**Comment by lkorth** [comment]
@ramanclabs has `1.3.0` fixed your runtime errors?

**Comment by lkorth** [comment]
Closing old issue. If you are still have this issue, please feel free to comment and we'll re-open it.

**Comment by rpblogs** [comment]
Hi ramanclabs, Could you let me know how you managed to run your braintree code in eclipse.
I am having the same issue when using braintree-api-1.7.8-full.jar while calling braintree.startPayWithPayPal().
Earilier i was using braintree-api-1.5.0-full.jar and it worked fine.

Please help

**Comment by gbramwell** [comment]
@rpblogs - At this moment, we officially support Gradle and Android Studio, and strongly encourage you to use our 2.+ SDK to stay up to date. The latest version brings many bug fixes and improvements.

If you have issues upgrading, feel free to [get in touch with our support team](https://www.braintreepayments.com/contact) for help.
