### ISSUE TITLE
Paypal in Braintree Drop In UI not Working 

### ISSUE THREAD

**Issue by maliksaif** [braintree/braintree_android#173]
I have been working on android Application and Integrated Paypal
it was working great before   i was able to proceed with sandbox and test the payment from past two days it is not working for both IOS and Android However payment with Visa Card is Working fine .
1- Everything was in Working condition before 3-4 days all of sudden paypal is not working Did not changed the code 
2- Package name does not have Underscores 
3- Stuck at the Browser Activity which says (Proceed with Sandbox) not opening up the onActivityResults gives no error both the Request code and OnActivityResult Snippet Attached
![image](https://user-images.githubusercontent.com/25033101/33809821-c400a6e0-de1e-11e7-9113-07a8332b59f6.png)

**Comment by quinnjn** [comment]
Hi @maliksaif. 

This issue seems related to [braintree-android-drop-in](https://github.com/braintree/braintree-android-drop-in). I'm going to close this issue and request that you move the issue to braintree-android-drop-in.

Also please:
 - fill in the issue template when you move the request! 
 - include all snippets as text! 

It makes it a lot easier for us to diagnose the problem.
