### ISSUE TITLE
Drop-in UI with Google Pay (from Android Pay)

### ISSUE THREAD

**Issue by jpage4500** [braintree/braintree_android#177]
I see docs talking about converting from Android Pay to Google Pay including this one:
https://www.braintreepayments.com/features/android-pay

Our app uses the drop-in UI which seems to still reference Android Pay. 
https://developers.braintreepayments.com/guides/drop-in/overview/android/v2

Is there an ETA for supporting Google Pay in drop-in UI?

Will apps using drop-in UI need to do anything to support Google Pay once supported?

**Comment by lkorth** [comment]
Support for Google Pay in braintree-android-drop-in was released yesterday in [3.2.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.2.0). 

In order to use Google Pay with Drop-in you'll need to ensure you are using Google Play Services Wallet 11.4.0 or later and supply a [`GooglePaymentRequest`](https://github.com/braintree/braintree-android-drop-in/blob/85bce2a73ccb447e1704e0a104aa4e68345ad3d5/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInRequest.java#L96) in your `DropInRequest`.
