### ISSUE TITLE
Unable to fined BraintreePaymentActivity Calass in Braintreen-api-1.2.7.jar

### ISSUE THREAD

**Issue by zubyf09** [braintree/braintree_android#18]
https://developers.braintreepayments.com/android+node/sdk/client/setup
I followed this link and add braintree-api1.2.7 into my project lib folder and then try to write this code
public void onBraintreeSubmit(View v) {
  Intent intent = new Intent(context, BraintreePaymentActivity.class);
  intent.putExtra(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN, clientToken);
  // REQUEST_CODE is arbitrary and is only used within this activity.
  startActivityForResult(intent, REQUEST_CODE);
}
It gives error on BraintreePaymentActivity.class cause in library there is no calass with this name....
so how i can fix this issue???

**Comment by gbramwell** [comment]
`BraintreePaymentActivity` is part of the `braintree` package, but not included in the `braintree-api` JAR. `braintree-api` is intended for anyone who wants to create their own UI from scratch rather than using our drop-in UI.

If you want to use `BraintreePaymentActivity`, you'll want to switch to using the `braintree` package. We strongly recommend using Gradle to pull in the project, which will use the AAR version of the library that includes all the assets you'll need. We do have a project ZIP available (http://search.maven.org/#browse%7C-1909860675), but can't guarantee we will continue to upgrade it as the ecosystem shifts to Android Studio and Gradle.

**Comment by zubyf09** [comment]
Thanks gbrmwell for reply 
So please can you tell me how to use Drop-in Ui.Because i want to use drop in UI
following this link https://developers.braintreepayments.com/android+node/sdk/client/drop-in
but this  funciton onBraintreeSubmit want to take su BrainTreePaymentActivity.class file Should i have to make may own actviity with this name.? Please guide me about drop-in-ui i am confuse in it.

**Comment by lkorth** [comment]
As @gbramwell stated, `BraintreePaymentActivity` exists in a separate package. In order to use Drop-In you will need to include [braintree-1.2.7.arr](http://search.maven.org/#browse%7C-1909860675) instead of braintree-api-1.2.7.jar. The documentation to set this up can be viewed at https://developers.braintreepayments.com/android+node/sdk/client/setup . Note: 1.2.7 is the last Drop-In release that will support Eclipse, if you are using Eclipse it will not be possible to use Drop-In after 1.2.7. If you are still having trouble, feel free to reach out to our support at [support@braintreepayments.com](mailto:support@braintreepayments.com)

**Comment by zubyf09** [comment]
Th Thanks man it's really helps me.Thanks again :)Muhammad Zubair AshrafCTO & FounderCC2, 5th floor Arfa Software Technology park Lahore – Pakistanhttp://virtualproz.com/
 M: 0346 631 3806
 Skype: zuby_f09 

     On Wednesday, January 28, 2015 10:51 PM, Luke Korth <notifications@github.com> wrote:
   

 As @gbramwell stated, BraintreePaymentActivity exists in a separate package. In order to use Drop-In you will need to include braintree-1.2.7.arr instead of braintree-api-1.2.7.jar. The documentation to set this up can be viewed at https://developers.braintreepayments.com/android+node/sdk/client/setup . Note: 1.2.7 is the last Drop-In release that will support Eclipse, if you are using Eclipse it will not be possible to use Drop-In after 1.2.7. If you are still having trouble, feel free to reach out to our support at support@braintreepayments.com—

**Comment by Sandhya21** [comment]
Hey,,I am integrating BrainTree into my Android app,But unable to do it on android studio,please enlist the jar,library or whatever required to add externally into my android stuio project.

**Comment by gbramwell** [comment]
@Sandhya21 Our [documentation for setting up the Android client](https://developers.braintreepayments.com/android/start/hello-client#android-sdk-setup) is the dependency you'll want to use in your `build.gradle` file.

If you have any questions as you integrate, our support team is happy to help! You can email them at support@braintreepayments.com or call at 877.434.2894.
