### ISSUE TITLE
Braintree activity-fragment not fully destroyed stays in the background

### ISSUE THREAD

**Issue by ema987** [braintree/braintree_android#189]
### General information

* SDK/Library version: 2.9.0
* Environment: Sandbox
* Android Version and Device: HTC One M7 (Android 6.0.1), OnePlus 3 (Android 7.1.2) - couldn't test on more devices

### Issue description

When creating a new payment request with the following code:

```
brainTreeFragment = BraintreeFragment.newInstance(activity, payPalClientToken)

            paymentMethodNonceCreatedListener = PaymentMethodNonceCreatedListener({
                presenter.onPayPalPaymentMethodNonceCreated(it)
            })
            brainTreeFragment!!.addListener(paymentMethodNonceCreatedListener)

            brainTreeErrorListener = BraintreeErrorListener({
                showMessage(R.string.error_complete_order_payment)
                enableBuyNowButton(true)
            })
            brainTreeFragment!!.addListener(brainTreeErrorListener)

            brainTreeCancelListener = BraintreeCancelListener({
                showMessage(R.string.canceled_payment)
                enableBuyNowButton(true)
            })
            brainTreeFragment!!.addListener(brainTreeCancelListener)

            val request = PayPalRequest(amount).currencyCode(currencyCode).intent(PayPalRequest.INTENT_AUTHORIZE)
            PayPal.requestOneTimePayment(brainTreeFragment, request)
```

the new fragment loads correctly to show PayPal checkout. Here is the strange behaviour.

If you press back, or tap the X at the left top to close the fragment, you go back to your app and if you open the task manager nothing's left.
If you press the link "Cancel payment and go back....." which is in the webview, you go back to your app but if you open the task manager you see there is another activity which is still running and wasn't completely killed. See screenshots attached. (Same happens also clicking other "cancel and go back" links which appear later in the checkout flow)

![braintree_stays_background](https://user-images.githubusercontent.com/9298564/35868836-025b656c-0b5e-11e8-877d-8ae0f48ecb2f.png)

![link_which_causes_the_issue](https://user-images.githubusercontent.com/9298564/35868870-1554bb82-0b5e-11e8-9b7a-52528d16e6ce.png)

**Comment by MKaslan1** [comment]
www.sandbox.paypal.com

**Comment by sdcoffey** [comment]
hey @ema987 ,

Sorry for letting your issue linger for so long without a response. Looks like we were missing an intent flag when starting the browser switch. If you were curious, we will need to add  `Intent.FLAG_NO_HISTORY` [this line](https://github.com/braintree/braintree_android/blob/master/PayPalOneTouch/src/main/java/com/paypal/android/sdk/onetouch/core/config/Recipe.java#L116) in PayPal One Touch. We'll get this out in our next release. I'm going to keep this open to track the work.

**Comment by ema987** [comment]
Hello @sdcoffey,

don't worry if you took your time, thanks for replying and letting me know what fixed the issue! That's much appreciated!

**Comment by sdcoffey** [comment]
Hey @ema987,

I have a quick update for you. It turns out that adding the flag I mentioned actually breaks integrations with password managers. We previously included these flags and subsequently [had to remove them](https://github.com/braintree/browser-switch-android/commit/3d4d950de82b6524b4d5fdc5a70790a38955a0a4) to support this use case. 

From that commit:
> If you switch to a password manager or try to use something like
1Password's password keyboard, the Chrome Custom Tab is killed as a
result of the Intent flags specified and the user has to start the flow
over from the beginning. This opts to leave the Chrome Custom Tab around
rather than break or degrade flows for password managers or
multitasking. This does make it possible for the user to revisit the
Chrome Custom Tab after they've finished their browser switch and switch
back to the app again causing a weird switch back where nothing happens.
This odd behavior can be mitigated by the page that returns the user to
the app by displaying a page that says everything is complete and
removing the button/link that switches back to the app.

Unfortunately, there's no way to resolve this without breaking this integration, which is an important use case. I'm going to close this issue, but if the workaround above doesn't work for you and you think of something better, by all means, send us a PR.
