### ISSUE TITLE
Paypal crash

### ISSUE THREAD

**Issue by sleith** [braintree/braintree_android#22]
Hi,
Previously my app didn't crash for the paypal. it just recently the app crash when trying to use paypal.
Here's the log:

```
03-21 22:08:59.795: E/AndroidRuntime(20978): java.lang.NullPointerException
03-21 22:08:59.795: E/AndroidRuntime(20978): 	at com.braintreepayments.api.PayPalHelper.buildPayPalConfiguration(PayPalHelper.java:136)
03-21 22:08:59.795: E/AndroidRuntime(20978): 	at com.braintreepayments.api.PayPalHelper.buildPayPalServiceIntent(PayPalHelper.java:153)
03-21 22:08:59.795: E/AndroidRuntime(20978): 	at com.braintreepayments.api.PayPalHelper.startPaypal(PayPalHelper.java:39)
03-21 22:08:59.795: E/AndroidRuntime(20978): 	at com.braintreepayments.api.BraintreeApi.startPayWithPayPal(BraintreeApi.java:108)
03-21 22:08:59.795: E/AndroidRuntime(20978): 	at com.braintreepayments.api.Braintree.startPayWithPayPal(Braintree.java:183)
```

I already install newest library 1.3.0, but still crash.
I use custom button. So the call is just 2 lines:

```java
braintree = Braintree.getInstance(this, clientToken);
braintree.startPayWithPayPal(this, PAYPAL_REQUEST_CODE);
```

Please help.
Thank you

**Comment by lkorth** [comment]
It looks like the client token you're using does not have PayPal enabled, the crash is happening when [reading PayPal configuration from the client token](https://github.com/braintree/braintree_android/blob/master/BraintreeApi/src/main/java/com/braintreepayments/api/PayPalHelper.java#L136). You'll want to double check the client token you're generating is for a merchant account that has enabled PayPal. `Braintree#startPayWithPayPal` should also not be called blindly, since PayPal could be disabled. You should always check [`braintree.isPayPalEnabled`](https://github.com/braintree/braintree_android/blob/master/BraintreeApi/src/main/java/com/braintreepayments/api/Braintree.java#L147) first as this will prevent any crashes like this.

**Comment by lkorth** [comment]
Closing this issue. If you still are having problems or have other questions, feel free to comment.
