### ISSUE TITLE
Any documentation on how to migrate/setup v3.0.0?

### ISSUE THREAD

**Issue by falcon4ever** [braintree/braintree_android#243]
Hi,

It looks like v3.0.0 was released 6 days ago according to: https://github.com/braintree/braintree_android/releases 

I was wondering if there is documentation available on how to migrate from v2 to v3 as the only instructions I can find are the older ones for v2 (the "Hello, Client!" in Readme.md still links to v2) https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2

The change log mentions:

- BraintreeFragment moves to the support fragment
- Requires AppCompatActivity to attach the BraintreeFragment to

so wondering what changes are required in the existing apps.

**Comment by quinnjn** [comment]
Hi @falcon4ever,

We're working on adding documentation. Because it is a major version bump it is a breaking change, but it should be small changes.

The biggest change is moving BraintreeFragment from the deprecated `android.app.Fragment` to the new `androidx.fragment.app.Fragment`.

Also migrated from the support library to [AndroidX](https://developer.android.com/jetpack/androidx/).

This is a breaking change since BraintreeFragment can no longer connect to an `Activity` and requires an `AppCompatActivity`.

We've also worked on removing deprecated code for the breaking change.

I'll leave this issue open until documentation is ready.

**Comment by quinnjn** [comment]
Braintree Android v3 docs are now available! 
- https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3
- https://developers.braintreepayments.com/guides/client-sdk/migration/android/v3

Payment method implementation docs are also updated for Braintree Android v3.

If there are any issues with the documentation, [let us know](https://developers.braintreepayments.com/help)!
