### ISSUE TITLE
Tokenize without a Fragment

### ISSUE THREAD

**Issue by erchenger** [braintree/braintree_android#245]
Hey Braintree Teamm, 
I am new to using Braintree but was wondering if there was a way that we could tokenize a card without having to create a Fragment. I may be missing some fundamental part of how your SDK/Service works, but it would be really fantastic if we didn't have to do this via a Fragment. 

It would be cool if I could create a `TokenizationClient` without `BraintreeFragment` that handled  `Configuration` and the `HTTPClient`. 

Cheers, 
Elliott

**Comment by crookedneighbor** [comment]
The way the sdk is set up, this is not possible. However, you can fork the repo and inspect the underlying http requests it is making and create your own sdk that does not use a fragment.

**Comment by quinnjn** [comment]
@erchenger for some more context on why we're using a Fragment to power Braintree.

- Access to the Activity lifecycle. This allows us to save/restore state and makes Braintree faster when returning from a configuration change.
- Proper access to the Activity for other payment providers that provide UI and may need to start additional Activities like Google Pay, Samsung Pay, and Visa Checkout.
- In addition to other payment providers providing UI, allowing the BraintreeFragment to `startActivityForResult` allows us direct access to the returned data from the payment provider instead of having to daisy chain it through your Activity.

The Fragment self manages its attaching to your Activity so there shouldn't have any additional work to support it. 

If we're missing out on a use case that is preventing you from using Braintree for Android let us know!

**Comment by erchenger** [comment]
@quinnjn thanks for the follow up. Ya so we really just use the `BraintreeFragment` for getting a `Nonce` of the card. So we don't show any of the UI elements (I am still new to my company so I am also learning more about what our needs are and what was built). One of the things that this is doing is forcing some of our architecture to be Android aware. When I dug into the `BraintreeFragment` I found all of the pieces that I would need to get a `Nonce` but I don't really want to fork y'alls SDK and maintain that myself just for that (at least for the time being ;-)). Totally understand that we are but one group making this request, so if it means I need to handle some of this on my end I am fine with that. 

I am starting to wonder if there is a way for me to rebuild the `nonce` functionality with components from your library without having to fork so that if we update the library we get compile time verification of changes. It wouldn't catch any of the side effects of deprecation, but assuming you use semver I can treat each version accordingly. 

It's been a week since I have looked in more depth, so I'll defer to you but if there was anyway we could `Nonce` a card without that overhead it would be great. Is `noncing` (that's a word right?) part of the state caching y'all are doing for `Activities`?

**Comment by quinnjn** [comment]
> Ya so we really just use the `BraintreeFragment` for getting a `Nonce` of the card.

That sounds like one of our most common use case, you can use the implementation [here](https://developers.braintreepayments.com/guides/credit-cards/client-side/android) for that.

> So we don't show any of the UI elements

Braintree Android doesn't show any UI.

> One of the things that this is doing is forcing some of our architecture to be Android aware.

Are you not building an Android app? If you're not, braintree_java can [process credit cards](https://developers.braintreepayments.com/reference/request/credit-card/create/java)

> I am starting to wonder if there is a way for me to rebuild the `nonce` functionality with components from your library without having to fork so that if we update the library we get compile time verification of changes. It wouldn't catch any of the side effects of deprecation, but assuming you use semver I can treat each version accordingly.

A total valid reason. I would also argue that this is a reason you shouldn't go against our suggested integration. For example, we have multiple HTTP clients that query Braintree differently depending on your Braintree configuration. This would all be encapsulated in BriantreeFragment for you. We do use semvar.

>  if there was anyway we could `Nonce` a card without that overhead it would be great

If you're building an Android app, there isn't really any additional overhead. BraintreeFragment is headless and doesn't show any UI. It's also pretty lightweight for your use case since it will just have a HTTP client for card processing. What overhead would you like to scale down?

> Is `noncing` (that's a word right?) part of the state caching y'all are doing for `Activities`?

You tokenize a payment method to get a nonce. No you shouldn't cache a nonce, it's meant as a short lived single use token to exchange for a payment method on your server.

I don't understand your use case still. If you're building an Android app you would still need an Activity, which is the only requirement for this library.

If you haven't tried an example integration you should spike one out and let us know what problems you have with the library and your use case. I think a lot of your questions will be resolved upon trying an example integration.

**Comment by erchenger** [comment]
@quinnjn thanks for the detailed response!

We are in fact building an Android app but we are trying to keep business logic outside of our Fragments/Activities. In doing so things like API requests and business logic have no understanding or connection to the UI and communicate via a `ViewModel` to get that to the presentation layer. Having said that I was asking initially because I didn't want to pass `Fragments/Activities` around our application in order to nonce cards and wanted to remove this logic from inside our Fragment (if possible). 

It sounds like using the Java SDK would be best for us because then we can nonce a card in our services layer and pass that back to our `ViewModels` if there are things we need to show in UI. 

Apologies for having not gone deeper in y'alls SDK and thanks for the info.

**Comment by crookedneighbor** [comment]
You cannot use the Java SDK with your android app, because you'd need to instatiate a bt gateway object with your api keys, and then you'd risk leaking your private api keys to your end users.

You can tokenize via the new Braintree GraphQL API: https://graphql.braintreepayments.com/

That would eliminate the need to use the sdk at all if you're just capturing card details. Contact our support team for assistance if you're having trouble with it. https://help.braintreepayments.com/

**Comment by erchenger** [comment]
Thanks for that feedback @crookedneighbor.
