### ISSUE TITLE
Untrusted Chain Error when connecting Braintree through Proxy

### ISSUE THREAD

**Issue by shibingr** [braintree/braintree_android#256]
### General information

* SDK/Library version: 2.14.2
* Environment: Sandbox
* Android Version and Device: All Android Devices
* Braintree dependencies: 
com.braintreepayments.api:braintree:2.14.2

### Issue description

We are facing issues in connecting to the Braintree server through a Wifi Router with a Proxy Setup. Please find the logs in the following :

E/Conscrypt: ------------------Untrusted chain: ----------------------
    == Chain0 == 
     Version:   3
E/Conscrypt:  Serial Number:   5d08b9641544ae3a167d0b6ec492e654
E/Conscrypt:  SubjectDN:   CN=payments.sandbox.braintree-api.com, OU=Braintree Production, O="PayPal, Inc.", L=San Jose, ST=California, C=US, SERIALNUMBER=3014267, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US, OID.2.5.4.15=Private Organization
06-20 15:12:15.736 25719-27279/com.modivmedia.scanitss.debug E/Conscrypt:  IssuerDN:   CN="Zscaler Intermediate Root CA (zscaler.net) (t) ", OU=Zscaler Inc., O=Zscaler Inc., ST=California, C=US

Is there any method to configure Proxy in the Braintree SDK or add the Proxy Certificate to the Trusted List.

**Comment by quinnjn** [comment]
A proxy won't help in this case since we pin the certificates to prevent any connection interceptions. Here is where we store the [pinned certificates for our GraphQL endpoints](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/internal/GraphQLConstants.java#L40), but there are more pinned certs for different endpoints.

I don't think we would want to add a way to include additional certificate pinning for development at this time.

The workaround to unblock your development is to custom build Braintree's SDK, adding your CA to those pinned certificates for development only.

**Comment by shibingr** [comment]
> A proxy won't help in this case since we pin the certificates to prevent any connection interceptions. Here is where we store the [pinned certificates for our GraphQL endpoints](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/internal/GraphQLConstants.java#L40), but there are more pinned certs for different endpoints.
> 
> I don't think we would want to add a way to include additional certificate pinning for development at this time.
> 
> The workaround to unblock your development is to custom build Braintree's SDK, adding your CA to those pinned certificates for development only.

Hi Quinnjn, 

We tried adding the adding the Certificate to the GraphQLConstants.java file. But still the Certificate issue persists. We used the Demo app in the SDK, added the certificate value and run the app. The Braintree connection is not going through while adding Credit/Debit card. A CertPathValidatorException is thrown. Please find the screenshot attached.

![screenshot](https://user-images.githubusercontent.com/9019599/60825217-33949100-a179-11e9-9204-a556e4f71079.png)


Thanks
Shibin
