### ISSUE TITLE
ThreeDSecure CardinalEnvironment NoClassDefFoundError: Failed resolution

### ISSUE THREAD

**Issue by tsulok** [braintree/braintree_android#272]
### General information

* SDK/Library version: 3.7.0
* Environment: Sandbox
* Android Version and Device: Google Pixel 2 with Android 10
* Braintree dependencies: 
'com.braintreepayments.api:braintree:3.7.0'

Test card used:
https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/ruby
"Successful Challenge Authentication"
Visa
- 4000000000001091
- 01/20**
- CVC: 123

### Issue description
Right after nonce was received from the server the 3DSecure initialization fails.

`val secureRequest = ThreeDSecureRequest().nonce(validation.cardNonce)
    .amount(validation.amount.toShortString(2))
     .versionRequested(ThreeDSecureRequest.VERSION_2)
   ThreeDSecure.performVerification(brainTreeFragment, secureRequest)`

SDK crashes:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/cardinalcommerce/cardinalmobilesdk/enums/CardinalEnvironment;
        at com.braintreepayments.api.ThreeDSecure.configureCardinal(ThreeDSecure.java:360)
        at com.braintreepayments.api.ThreeDSecure.access$100(ThreeDSecure.java:46)
        at com.braintreepayments.api.ThreeDSecure$4.onConfigurationFetched(ThreeDSecure.java:223)
        at com.braintreepayments.api.BraintreeFragment$14.run(BraintreeFragment.java:829)
        at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:752)
        at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:821)
        at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:188)
        at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:162)`

**Comment by sestevens** [comment]
Hi @tsulok, did you follow the [3DS Secure guide](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3) in the docs? I'm wondering if you missed the step to add the Cardinal Commerce dependency to your app level build.gradle file.

It should look like this:

```groovy
repositories {
    maven {
        url "https://cardinalcommerce.bintray.com/android"
        credentials {
            username 'braintree-team-sdk@cardinalcommerce'
            password '220cc9476025679c4e5c843666c27d97cfb0f951'
        }
    }
}

```

**Comment by tsulok** [comment]
Hey @sestevens, thanks for getting back.

Yes the linked maven repository is listed under an other maven repository (jitpack) in the top level build gradle file.
```
repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven {
            url "https://cardinalcommerce.bintray.com/android"
            credentials {
                username 'braintree-team-sdk@cardinalcommerce'
                password '220cc9476025679c4e5c843666c27d97cfb0f951'
            }
        }
    }
```

I've checked and until version 3.5.0 everything works. However I have the same issue with 3.6.0

**Comment by tsulok** [comment]
Hey @Epreuve,

I found the problem. I don't use your `drop-in` project which has a dependency on the `three-d-secure` project which depends on the `cardinalmobilesdk`.

After I added your latest available three-d-secure project to my dependencies the cardinal sdk downloaded properly.

It might worth a note on the integration page / here in the repo that users should implement that project, otherwise it won't work.

Thanks,
David

**Comment by Epreuve** [comment]
@tsulok We list the `three-d-secure` module as a dependency [here in our docs](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#custom-ui), was there another place you had been referencing that we didn't call that out?

I had initially thought that might be the issue, but wasn't sure as without the module, I wasn't able to get my demo project to build.  Since you'd mentioned the issue occurring after receiving a nonce, I continue looking and attempting to replicate.

We might need to revisit adding the check for the Cardinal SDK back, to provide better and more immediate feedback around this in future version, so we'll take another look at that.

**Comment by tsulok** [comment]
Hm it is clearly there, sorry for the trouble, I'm closing this issue.

Thank you for your help

**Comment by kingargyle** [comment]
The correct thing to do here is if your have a dependency, is make sure the POM file that is being generated and uploaded to maven central, specifies all the dependencies that are needed.  This way they are automatically brought in.   Otherwise people will keep running into this issue and have to try to find it in the docs.
