### ISSUE TITLE
com.nimbusds:nimbus-jose-jwt@7.0.1 has a security vulnerability

### ISSUE THREAD

**Issue by alosdev** [braintree/braintree_android#289]
### General information

* SDK/Library version: 3.7.2
* Environment: Sandbox
* Android Version and Device: not relevant
* Braintree dependencies: 
com.braintreepayments.api:braintree:3.7.2

### Issue description

according to https://snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-536068 the used library com.nimbusds:nimbus-jose-jwt@7.0.1 has an Improper Check for Unusual or Exceptional Conditions.
could I locally update to version 7.9 for my application without any problems? Will you consider a fixed release?

**Comment by sestevens** [comment]
Hi @alosdev, `nimbus-jose-jwt` is used by CardinalMobile, which is a dependency of the Braintree SDK that does 3D Secure verification. We did a brief test using version 7.9 of `nimbus-jose-jwt`, and while we didn't notice any issues, we can't guarantee that updating to this version will work consistently since we don't own the CardinalMobile library.

There is a new version of the CardinalMobile library that we'd like to update to, but we're currently working with Cardinal to resolve an issue with that version.

**Comment by alosdev** [comment]
@sestevens thanks for the update but closing the issue without a solution doesn't feel right. could you at least leave it open till there is a new version and close it then?

**Comment by sestevens** [comment]
@alosdev Sure, I'll reopen the issue. I'm not sure if/when we'll have a specific update on this since we don't own the CardinalMobile SDK. We can certainly follow up with them and post any response we get here.

**Comment by scannillo** [comment]
Hi @alosdev. You can try updated to [Android v3.9.0](https://github.com/braintree/braintree_android/releases/tag/3.9.0) where we update to the latest version of CardinalMobile, though they didn't note any dependency updates in their CHANGELOG.

Also, we did reach out to CardinalMobile with this concern and they weren't able to provide us any details on the dependencies they're baking into their SDK. So - we unfortunately don't have a ton of ways to circumvent the issue you're seeing right now. Because of this, I am going to close this issue.

Please keep us posted of any future issues, if they come up!
