### ISSUE TITLE
Relax BraintreeFragment.newInstance to accept FragmentActivity

### ISSUE THREAD

**Issue by TWiStErRob** [braintree/braintree_android#290]
### General information

* SDK/Library version: 3.8.0
* Environment: code, so any
* Android Version and Device: any
* Braintree dependencies:
implementation "com.braintreepayments.api:braintree:3.8.0"

### Issue description
There was a change in 3.x to require `AppCompatActivity` as the first argument in `BraintreeFragment.newInstance`, however the only method called on it is `getSupportFragmentManager`, which is declared on `FragmentActivity`. Is there any reason to require that specific type?

**Comment by sshropshire** [comment]
Hey @TWiStErRob thanks for using the Braintree SDK for Android.

In regards to `BraintreeFragment.newInstance`, there is an [existing overload](https://github.com/braintree/braintree_android/blob/6f472fcbcde8a016176f933ec25d35adc3389fb6/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L160) that allows you to pass an Android Fragment instead of an `AppCompatActivity` reference.

Does this resolve the issue?

**Comment by TWiStErRob** [comment]
That means nested fragments. There's no way currently to have a `class MyActivity extends FragmentActivity` with just a `BraintreeFragment` inside it.

**Comment by sshropshire** [comment]
@TWiStErRob correct, I now see the concern.

May I ask, is there any particular reason you require the use of `FragmentActivity` over its `AppCompatActivity` subclass?

**Comment by scannillo** [comment]
Hi @TWiStErRob. We made updates to allow new `BraintreeFragment` instances to be created using `FragmentActivity`. We'll have a new version of the SDK released soon 👍

**Comment by sshropshire** [comment]
Resolved in v3.10.0.
