### ISSUE TITLE
How to alter to my own sandbox braintree merchant account to do a testing payment?

### ISSUE THREAD

**Issue by blacksabbather** [braintree/braintree_android#292]
### General information

* SDK/Library version: Latest
* Environment: sandbox
* Android Version and Device: Android 10
* Braintree dependencies: 
com.braintreepayments.api:braintree:3.9

### Issue description

Actually this is a question rather than a issue. 
I'm helping a merchant to implement a demo for Braintree checkout on Android. I imported https://github.com/braintree/braintree_android/tree/master/Demo and able to display the UI. But I have difficulty to change the PayPal account when I try to click 'PayPal' to do a checkout. I noticed the demo seems to be bounded with the receiving account id **dcpspy2brwdjr3qn** according to https://braintree-sample-merchant.herokuapp.com/config; And the buyer seems to be locked to **bt_buyer_us@paypal.com**

![image](https://user-images.githubusercontent.com/33573782/77620654-caa6b080-6f75-11ea-84f6-4f83433d72f1.png)

![image](https://user-images.githubusercontent.com/33573782/77620685-ddb98080-6f75-11ea-9d47-60e88a585e9c.png)

What I want to do:
1. Allow me to use a different PayPal account to log in as buyer
2. I already set up REST URL (getClientToken and transaction process)and already has a sandbox BT account. How to switch from the default URL and default merchant to my own backend web service and my own sandbox BT account
Could you please shed some some lights on how to enable PayPal account change?

**Comment by sestevens** [comment]
@blacksabbather Our demo app uses a specific merchant ID, and it's not build for this to be changed easily. I'd recommend creating your own demo app, perhaps based on this one, so that you can make the changes you need.

**Comment by blacksabbather** [comment]
Thank you for the reply. Is https://github.com/braintree/braintree-android-drop-in a better option to initialize and configure to offer to change the merchant ID and allow using sandbox PayPal account?

**Comment by sestevens** [comment]
Drop-in is certainly an easier/faster option since the UI is taken care of for you. If you'd like, you can change the server URL used by the demo app in [Settings.java](https://github.com/braintree/braintree-android-drop-in/blob/fb4cba21357a29227fa8351c619904435278b787/Demo/src/main/java/com/braintreepayments/demo/Settings.java#L16). However, you'll need to make sure that the paths available at that URL make what the demo app expects, and that the JSON returned is in the expected structure. There's a similar [Settings.java](https://github.com/braintree/braintree_android/blob/36d073159886af37ef914d33858a62582f6f80fd/Demo/src/main/java/com/braintreepayments/demo/Settings.java#L14) class in the demo app for this repo as well.

There isn't a straightforward way to just change the merchant ID used, since the merchant ID is set server-side, not in the demo app itself.
