### ISSUE TITLE
Can Android jump to the payment page through webview

### ISSUE THREAD

**Issue by panchao0716** [braintree/braintree_android#352]
hi！Can Android jump to the payment page through webview, instead of jumping to an external browser to pay

**Comment by sarahkoop** [comment]
Hi @panchao0716 thanks for using the Braintree Android SDK! More information would be helpful to understand this request. Are you asking about the PayPal payment flow? Which version of the SDK are you using?

**Comment by panchao0716** [comment]
@sarahkoop yes，I want to know the PayPal payment process，The sdk version is “implementation 'com.braintreepayments.api:drop-in:4.6.0'”，Can I only jump to the browser for payment?

**Comment by sshropshire** [comment]
@panchao0716 this is the current way it works at the moment, yes. We're using a Chrome Custom tab so that if a PayPal user is already authenticated, it makes the process smooth for the user to confirm their purchase without having to re-enter their account credentials. WebViews would not allow us to do so.

**Comment by sarahkoop** [comment]
Closing this since it's not on our roadmap to switch from Chrome Custom tabs to WebView.
