### ISSUE TITLE
BrainTreeBrowserSwitchActivity is missing in flutter

### ISSUE THREAD

**Issue by UsamaKabeer07** [braintree/braintree_android#372]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:

**Comment by sarahkoop** [comment]
Hi @UsamaKabeer07 thanks for using the Braintree Android SDK. We don't have official support for Flutter, so if you are using a Flutter plugin, this issue may be better directed there. Closing this for now.  If this issue is related to the Braintree Android SDK, please reopen including the information in the issue template we have provided.

**Comment by UsamaKabeer07** [comment]
Okay no problem
