### ISSUE TITLE
Drop In PayPal not working in Android 11(please do not close this ticket with out resolving this issue).

### ISSUE THREAD

**Issue by khalil05400** [braintree/braintree_android#413]
I have integrated Braintree into my android application. I am using drop-in UI. But when I click on the "Checkout With PayPal" Button the BrainTreePayment Activity finishes and onActivityResult is called with resultCode being 0. It does not return any error. It does not open the PayPal application or browser.

Note: This issue is happening in only Android 11

Please help me resolve this issue.

**Comment by sshropshire** [comment]
Sample Template:



### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:








### Issue description

**Comment by khalil05400** [comment]
Brain tree drop in
4.6.0
Android sdk 11
Api level 30
Gradle 4.1.3

**Comment by sshropshire** [comment]
Hi @khalil05400 thanks for using the Braintree SDK for Android. I would recommend updating to the latest `com.braintreepayments.api:drop-in:5.2.1` version of the DropIn library. Also since this is for DropIn, if the issue still persists after upgrading please open an issue in our [DropIn repo](https://github.com/braintree/braintree-android-drop-in/issues/new).

**Comment by santhoshvgts** [comment]
Is is this issue fixed ?

**Comment by sshropshire** [comment]
Can you update to version `6.0.2` of DropIn and send a video reproducing the unexpected behavior?
