### ISSUE TITLE
PayPal redirection is blocked by a browser dialog with alert message

### ISSUE THREAD

**Issue by Hector1990** [braintree/braintree_android#611]
### General information

* SDK/Library version:  4.17.0
* Environment: Production and Sandbox
* Android Version and Device: Oneplus 7 pro with Android 12 (Huawei devices or some devices without Chrome browsers)
* Braintree dependencies:
    - com.braintreepayments.api:data-collector:4.17.0
    - com.braintreepayments.api:paypal:4.17.0

### Issue description

In normal cases, when the user completes the payment behavior, it will be redirected to the product app automatically. 

But on some devices, there will be a dialog blocking the redirection behavior. You can see the video. We believe that will be a big effect on the user experience. Is there any way to prevent this?

 

https://user-images.githubusercontent.com/14172847/196904832-6961d5a3-30ce-49cb-a5ee-e49708f3784d.mp4

**Comment by sshropshire** [comment]
Hi @Hector1990 thanks for using our SDK. This seems like a security dialog presented by the OnePlus browser. Very similar to how [iOS does it](https://stackoverflow.com/q/33242557) as well.

If the user selects "Open" does it work as expected?

**Comment by Hector1990** [comment]
@sshropshire Hi, it works as expected as the user selects "Open". But some users maybe don't notice it. And from the data we track, this amount is not low.

We also integrated PayPal through Adyen previously, they provided a redirect URL so that we can open PayPal in the webview inside our app. It works fine.

So, could you open PayPal in the webview instead of the browser?

**Comment by sshropshire** [comment]
@Hector1990 understood. I believe the original reason why we chose to open via Chrome Custom Tabs / Browser is because of an InfoSec requirement. It is unfortunate but it may be the behavior of that particular browser. Is this reproducible with Chrome?

Otherwise, the only thing I can think of that may help is if we provide support for Android [App Links](https://developer.android.com/training/app-links). It does require more setup on the merchant side, so we haven't considered this yet. It may be something for us to look into and get prioritized.

**Comment by Hector1990** [comment]
@sshropshire Thanks a lot! I believe it will be a great help to us.

**Comment by saperi22** [comment]
Support for App Links has been added. Please checkout our latest v5 SDK versions here : https://github.com/braintree/braintree_android/releases.
