### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by sudipn3002** [braintree/braintree_android#690]
### Braintree SDK Version

6.8.0

### Environment

Sandbox

### Android Version & Device

12

### Braintree dependencies

'com.braintreepayments.api:drop-in:6.8.0'

### Describe the bug

6011000180331112 please test this card no .validation is not working on first screen properly

### To reproduce

add card section

### Expected behavior

validation should show in first screen

**Comment by sshropshire** [comment]
@sudipn3002 thanks for using the Braintree SDK for Android. This card fails because it isn't a valid test card for the Braintree Gateway. Here's a [list of valid test cards](https://developer.paypal.com/braintree/docs/guides/credit-cards/testing-go-live/java) to use. There's also a [list of 3DS Test cards](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live) available as well. Closing this for now.
