### ISSUE TITLE
UnexpectedException for umlaut in cardholdername

### ISSUE THREAD

**Issue by marlonbosse** [braintree/braintree_android#85]
I got a problem with cardholdernames containing umlaut like 'ä' . 

```java
CardBuilder cardBuilder = new CardBuilder()
				.cardNumber(creditCard.cardNumber)
				.expirationDate(creditCard.expirationDate.toMMYYWithSeparator())
				.cardholderName(creditCard.ownerName)
				.cvv(creditCard.cvc);
			braintreeFragment = BraintreeFragment.newInstance(this, clientToken.getClientToken());
			Card.tokenize(braintreeFragment, cardBuilder);
```

In the onError-Callback I get the mentioned UnexpectedException with a empty message. Since I don't get an ErrorWithResponse this doesn't seem to be an issue with umlaute in cardholdername. 

 The [braintree reference website](https://developers.braintreepayments.com/reference/general/exceptions/java) indicates a bug with the client library.

**Comment by lkorth** [comment]
@marlonbosse: thanks for submitting this issue. This error is being generated from a 400 HTTP response because of the special character. We're currently looking into if we want to allow special characters in the cardholder name. Either way, we will make sure to update this issue, update the reference docs with the allowed character set, and improve the error message or accept the characters.

Note: the reference section is referring to [braintree_java](https://github.com/braintree/braintree_java) and not this SDK.

**Comment by marlonbosse** [comment]
@lkorth thanks for the quick reply. So the quick fix will be sanitizing the input. Looking forward to the update.

**Comment by lkorth** [comment]
@marlonbosse: We've fixed this issue. The fix will go out in the next release.
