### ISSUE TITLE
Absurd Migration Requirements

### ISSUE THREAD

**Issue by jktestaccount** [braintree/braintree_android#928]
### Braintree SDK Version

4.24

### Environment

Sandbox

### Braintree dependencies

braintree

### Describe the bug

Your Braintree Android v4.9.0+ Migration Guide is absolutely absurd!!!!!!!!!!!!!!! A massive amount of work required to migrate - and mostly it appears change for the sake of change. The document is nearly unreadable too with no detailed instructions.

Braintree used to be a wonderful company, but since acquisition by PAYHELL, it has devolved into a cesspool which can only be created by the likes of Paypal - I take comfort in the fact that paypal is facing a serious decline in revenue. Personally I stopped using paypal more than a decade ago due to the incredibly unethical business practices. I will beg our client to move their app another payment solution as supporting this SDK is not feasible and nor is dealing with Paypal from a business perspective.

### To reproduce

Use paypal!

### Expected behavior

Rational

**Comment by sshropshire** [comment]
@jktestaccount thanks for using the Braintree SDK for Android. I'd love to hear more about your experience. A lot of the changes we made for v4.9.+ were due to Google deprecating `startActivityForResult()`.

There is a reason for every decision we make, and honestly we're trying our best just like everyone else out there. We're working to improve the SDK as much as we can to support all the different possible ways there are to build an Android app.

If you have any suggestions or feedback on the parts of the migration guide that are unclear, please feel free to re-open this issue.
