### ISSUE TITLE
Is it possible to open PayPal authorization not in full screen?

### ISSUE THREAD

**Issue by romanmikhailov** [braintree/braintree_android#99]
We have a purchase form with fixed size (~half of screens dimensions) in the centre of screen.

During Braintree integration I met next requirement:
> Is it possible to make PayPal authorisation screen the same size as purchase form?

So, Is it possible to control the size of PayPal authorisation screen size?

**Comment by sdcoffey** [comment]
Hey @romanmikhailov,

Thanks for bringing this up. Due to our PCI compliance requirements, we don't allow PayPal authorization to happen in the same process as the containing app, which is why PayPal auths will app switch either to the browser or the PayPal Wallet app, if it's installed. Sorry for the inconvenience, let us know if there's anything else we can do to make your integration a little easier.
